### ISSUE TITLE
change coder.local to an another custom word

### ISSUE THREAD

**Issue by morpheusu** [googlecreativelab/coder#81]
Hi there, I am working on coder v0.6 two weeks ago and I would like to change the "coder.local" to "customword.local".
 Is there a few lines to change in code to make this real ?
If changes the code to do this, also will change in terminal the pi@coder to pi@customword ?

**Comment by danpillay87** [comment]
Hi there, have tried this also however seems like it is being overwritten back to default each time on reboot - not sure what's doing that, any ideas? @morpheusu did you manage to have success with this?

**Comment by CVBruce** [comment]
Hi,
If you look in /boot, you'll see a folder that is named something like coder or coderdeafults.  Poke around in there (only a couple of files), and you'll see one that contains the default hostname.  Change it there also.

**Comment by CVBruce** [comment]
Ok, I just took a look, the folder name is "coder_settings", in that folder, there is a file named hostname.txt that must be changed.  I think they set it up this way so that you could put the sd card into a windows computer and change the settings, with out having extra software that would allow you to mount the ext4 partition.  It's a neat trick, I only wish there were more things that one could set up this way.
