### ISSUE TITLE
Consider switching to bcrypt-nodejs

### ISSUE THREAD

**Issue by mpegram3rd** [googlecreativelab/coder#82]
I created a fork of the project with an eye towards trying to create a portable version of coder that could easily be zipped up and run on multiple OS's/machines.   There were 2 machine specific obstacles I encountered in the process: socket.io and bcrypt.  It turns out bcrypt as used by the app can be replaced with a non-binary pure nodejs implementation by simply swapping out the dependency for "bcrypt-nodejs".   It may not be "as fast" but I doubt you'll notice any real world difference.

This was done to make it easier for kids in a coder dojo to be able to walk out with a copy of "coder" to continue their hacking at home.

**Comment by jmstriegel** [comment]
Thanks for the tip (and sorry I'm getting around to this so late). I tried this out while preparing the latest release and it was pretty slow on the older Pi hardware. That said, I've tweaked the package.json and auth app for the non-pi version to use bcrypt-nodejs, so that'll work for you on other platforms. For now, I think the Pi version will need to stay with the standard bcrypt module.

**Comment by mpegram3rd** [comment]
Thanks for the follow up.  I'll definitely check out the new version!
